services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beauty_salon
      TZ: Europe/Moscow


  web:
    build: .
    ports:
      - "8000:8000" # Оставляем только порт для сайта
    environment:
      # Обратите внимание: хост теперь 'db' (внутреннее имя в Docker)
      DATABASE_URL: "postgresql+asyncpg://user:password@db/beauty_salon"
    depends_on:
      - db